import 'server-only';
import { requireUser } from './auth';
import type { MrpHeader,MrpMaterial,MrpProduct } from './mrp';
export async function mrpContext(){const {db}=await requireUser();let products:any[]=[],headers:any[]=[];
 for(let o=0;;o+=500){const r=await db.from('product_skus').select('id,sap_material_code,active,product_models!inner(catalog_name_original,reference_code)').order('id').range(o,o+499);if(r.error)throw new Error('No se pudieron consultar productos.');products.push(...r.data);if(r.data.length<500)break;}
 for(let o=0;;o+=1000){const r=await db.from('sap_bom_headers').select('id,parent_material_code,center,alternative,base_quantity,base_unit,active').eq('active',true).order('id').range(o,o+999);if(r.error)throw new Error('No se pudieron consultar listas SAP.');headers.push(...r.data);if(r.data.length<1000)break;}
 return {products:products.map(p=>({id:p.id,name:p.product_models.catalog_name_original,code:p.sap_material_code,referenceCode:p.product_models.reference_code})) as (MrpProduct&{referenceCode:string|null})[],headers:headers.map(h=>({id:h.id,code:h.parent_material_code,center:h.center,alternative:h.alternative,base:h.base_quantity,unit:h.base_unit,active:h.active,items:[]})) as MrpHeader[]};
}
export async function loadMrpMaterials():Promise<MrpMaterial[]>{const {db}=await requireUser();let rows:any[]=[];for(let o=0;;o+=1000){const r=await db.from('materials').select('*,material_families(family_name,subfamily_name)').order('id').range(o,o+999);if(r.error)throw new Error('No se pudo consultar el maestro de materiales.');rows.push(...r.data);if(r.data.length<1000)break;}
 return rows.map(m=>({id:m.id,code:m.sap_code,description:m.sap_description_original,family:m.material_families?[m.material_families.family_name,m.material_families.subfamily_name].filter(Boolean).join(' / '):null,classification:m.mrp_classification,active:m.active,purchaseUnit:m.purchase_unit,conversionFromUnit:m.conversion_from_unit,unitsPerPurchase:m.units_per_purchase,conversionConfirmed:m.conversion_confirmed}));
}
export async function loadMrpItems(headers:MrpHeader[]){const {db}=await requireUser();return Promise.all(headers.map(async h=>{const items:any[]=[];for(let o=0;;o+=1000){const r=await db.from('sap_bom_items').select('*').eq('sap_bom_header_id',h.id).order('id').range(o,o+999);if(r.error)throw new Error('No se pudieron leer componentes SAP.');items.push(...r.data);if(r.data.length<1000)break;}return {...h,items:items.map(i=>({id:i.id,code:i.component_code,description:i.component_description,quantity:i.component_quantity,unit:i.component_unit,sourceRow:i.source_row,position:i.position}))};}));}
