import Link from 'next/link';
import { requireUser } from '@/lib/auth';
export default async function Products({ searchParams }: { searchParams: Promise<{ q?: string; page?: string }> }) {
  const { db } = await requireUser(); const params = await searchParams;
  const q = (params.q ?? '').replace(/[%_,()]/g, '').slice(0,80); const page = Math.max(1, Math.min(100000, Number(params.page) || 1));
  let query = db.from('product_skus').select('id,commercial_measure,width_cm,length_cm,height_cm,sap_material_code,sap_name_original,engineering_bom_status,sap_bom_status,reconciliation_status,product_models!inner(catalog_name_original,product_line)', { count:'exact' }).eq('product_models.product_line','RESORPEDIC').order('id').range((page-1)*30,page*30-1);
  if (q) query = query.or(`sap_material_code.ilike.%${q}%,sap_name_original.ilike.%${q}%`);
  const { data, count, error } = await query;
  return <><div className="page-heading"><div><p className="eyebrow">MAESTRO DE PRODUCTO</p><h1>Productos Resorpedic</h1><p className="muted">Modelos y SKU registrados en la base de datos.</p></div><Link className="button" href="/pilot">Consultar piloto 101</Link></div><section className="panel"><form className="filters"><label>Buscar por código o nombre SAP<input name="q" defaultValue={q} placeholder="Código o nombre del producto"/></label><button className="primary">Buscar</button></form>{error ? <p className="alert error">No fue posible consultar productos. Revisa el estado del sistema.</p> : !data?.length ? <div className="empty-state"><h3>{q ? 'No hay coincidencias' : 'Todavía no hay productos registrados'}</h3><p>El piloto está disponible para revisión en el explorador BOM. La carga general requiere resolver los conflictos de identidad.</p><Link href="/pilot">Ver datos reales del caso piloto →</Link></div> : <div className="table-scroll"><table><thead><tr><th>Modelo / SAP</th><th>Medida</th><th>Dimensiones</th><th>BOM ingeniería</th><th>BOM SAP</th><th>Reconciliación</th></tr></thead><tbody>{data.map(s => <tr key={s.id}><td><Link href={`/products/${s.id}`}>{s.sap_name_original || s.sap_material_code || 'Sin nombre SAP'}</Link><br/><small>{s.sap_material_code || 'Sin SAP'}</small></td><td>{s.commercial_measure ?? 'Pendiente'}</td><td>{s.width_cm ?? '?'} × {s.length_cm ?? '?'} × {s.height_cm ?? '?'}</td><td>{s.engineering_bom_status}</td><td>{s.sap_bom_status}</td><td>{s.reconciliation_status}</td></tr>)}</tbody></table></div>}<div className="pagination"><span>{count ?? 0} SKU · página {page}</span>{page>1 && <Link href={`?q=${encodeURIComponent(q)}&page=${page-1}`}>Anterior</Link>}{(count ?? 0)>page*30 && <Link href={`?q=${encodeURIComponent(q)}&page=${page+1}`}>Siguiente</Link>}</div></section></>;
}
