import Link from 'next/link';
import { ArrowUpRight, GitBranch } from 'lucide-react';
import { requireUser } from '@/lib/auth';
export default async function Dashboard() {
  const { db } = await requireUser();
  const results = await Promise.all(['product_models','product_skus','engineering_boms','materials'].map(t => db.from(t).select('id',{ count:'exact', head:true })));
  const labels = ['Modelos registrados','SKU registrados','BOM de ingeniería','Materiales registrados'];
  return <><div className="page-heading"><div><p className="eyebrow">LAMITEX / CONTROL DE PRODUCTO</p><h1>De la fuente a la estructura</h1><p className="muted">Estado de los datos registrados en el ERP.</p></div><Link className="button primary" href="/material-lists?q=3C83010">Ver listas de materiales <ArrowUpRight size={16}/></Link></div><div className="metrics">{results.map((r,i) => <div key={labels[i]}><span>{labels[i]}</span><strong>{r.error ? '—' : r.count}</strong><small>{r.error ? 'No se pudo consultar' : 'Supabase · datos persistidos'}</small></div>)}</div><section className="feature-panel"><div><p className="eyebrow">PRIMER CASO DE VALIDACIÓN</p><h2>Pocket Boreal<br/>Memory Foam</h2><p>Recorre los diez componentes del árbol de ingeniería y comprueba cada relación contra el Excel original.</p><Link className="button primary" href="/pilot">Abrir explorador <ArrowUpRight size={16}/></Link></div><div className="feature-structure"><GitBranch size={42} strokeWidth={1.3}/><h3>Producto → SKU → BOM</h3><p>Ingeniería y SAP en vistas independientes</p><span className="badge warning">Excel corregidos disponibles</span></div></section><div className="two-columns"><section className="panel"><p className="eyebrow">TRAZABILIDAD</p><h2>Validar antes de importar</h2><p>El caso piloto es una extracción verificable de los archivos originales. Las cifras superiores cuentan exclusivamente registros guardados en la base.</p><Link href="/quality">Revisar calidad de datos →</Link></section><section className="panel"><p className="eyebrow">SIGUIENTE ETAPA</p><h2>Planificación con fundamentos</h2><p>El MRP bruto consolida las listas SAP por código y unidad. Plan maestro e inventario corresponden a las próximas etapas.</p><Link href="/mrp">Calcular requerimiento de materiales →</Link></section></div></>;
}

