import Link from 'next/link';
import { requireUser } from '@/lib/auth';
import pilot from '@/data/pilot.json';
import { SourceUpload } from '@/components/source-upload';
import { importPilot } from './actions';
export default async function Imports({searchParams}:{searchParams:Promise<{error?:string}>}){
  const {db,profile}=await requireUser();const {error}=await searchParams;const canWrite=['ADMIN','ENGINEERING'].includes(profile.role);
  const archived=await db.from('imports').select('file_name,file_hash,status').eq('import_type','SOURCE_ARCHIVE').eq('status','STAGED').in('file_hash',pilot.sources.map(s=>s.sha256));
  const ready=!archived.error&&pilot.sources.every(s=>archived.data?.some(a=>a.file_hash===s.sha256&&a.file_name===s.file));
  return <><p className="eyebrow">FUENTES ORIGINALES / CASO PILOTO</p><h1>Importar datos</h1><p className="muted">Archivo original → verificación → revisión humana → persistencia transaccional.</p>{error&&<p className="alert error" role="alert">{error==='confirm'?'Debes confirmar la asociación del piloto.':error==='role'?'Tu rol no permite importar.':'No se pudo guardar el piloto. Comprueba que las cuatro fuentes estén archivadas, la migración esté aplicada y que el SKU no exista ya. Ningún registro parcial del piloto se guardó.'}</p>}<section className="panel"><h2>BOM SAP / Materiales</h2><p>Actualiza las listas SAP y relaciona productos existentes por código exacto. El módulo de ingeniería conserva sus datos actuales.</p><Link className="button primary" href="/material-lists/import">Importar Excel SAP actualizado</Link></section><details><summary>Importación histórica del piloto</summary><div className="two-columns"><section className="panel"><h2>1. Archivar las fuentes</h2><p>Los archivos se conservan en almacenamiento privado. Solo se aceptan las versiones que coincidan con las huellas auditadas.</p>{pilot.sources.map(s=><div className="source-row" key={s.file}><strong>{s.file}</strong><p className="footnote">{archived.data?.some(a=>a.file_hash===s.sha256)?'Archivado y verificado':'Pendiente de cargar'}</p></div>)}{canWrite?<SourceUpload/>:<p className="alert">Tu rol permite consultar; solicita la importación a Ingeniería o Administración.</p>}</section><section className="panel"><h2>2. Revisar e importar el piloto</h2><p>1 modelo · 1 SKU · 1 BOM de ingeniería · 10 nodos · 1 BOM SAP · 19 registros SAP.</p><p>El ID 101 ya tiene un único candidato en el Excel corregido. Se guardará exclusivamente Pocket Boreal, SAP 3C83010, con componentes 1–10. La unidad de cantidad y de lead time quedan pendientes; el BOM permanecerá en borrador.</p><Link href="/pilot">Revisar árbol, fuentes y reconciliación →</Link><form action={importPilot}><label className="inline-check" style={{margin:'25px 0',alignItems:'flex-start'}}><input type="checkbox" name="confirm" value="yes" required disabled={!canWrite||!ready}/>He revisado las fuentes y confirmo la asociación de los componentes 1–10 al SKU 3C83010, 105 × 190 × 38 cm.</label><button className="primary" disabled={!canWrite||!ready}>Confirmar e importar solo este caso</button></form>{!ready&&<p className="footnote">Se habilitará cuando las cuatro fuentes estén archivadas.</p>}<p className="alert">La importación masiva permanece bloqueada hasta resolver las identidades repetidas y revisar las unidades. Los 18.199 registros SAP corregidos se pueden consultar en Listas / Requerimiento; esta operación registra únicamente el piloto.</p></section></div></details></>;
}

