import Link from 'next/link';
import { listEngineering,requireEngineerPage } from '@/lib/engineering-server';
import { requireUser } from '@/lib/auth';
export async function EngineeringDirectory({admin=false,q='',page='1',state='ACTIVE'}:{admin?:boolean;q?:string;page?:string;state?:string}){
 const {db}=admin?await requireEngineerPage():await requireUser();const all=await listEngineering();
 const matches=all.filter(b=>(state==='ALL'||b.lifecycle===state)&&`${b.product_skus.product_models.catalog_name_original} ${b.product_skus.product_models.reference_code??''} ${b.product_skus.sap_material_code??''}`.toLowerCase().includes(q.toLowerCase()));
 const current=Math.min(Math.max(1,parseInt(page)||1),Math.max(1,Math.ceil(matches.length/20)));const visible=matches.slice((current-1)*20,current*20);
 const stats=await Promise.all(visible.map(async b=>{const count=await db.from('engineering_bom_nodes').select('id',{count:'exact',head:true}).eq('engineering_bom_id',b.id).eq('active',true);const depth=await db.from('engineering_bom_nodes').select('calculated_level').eq('engineering_bom_id',b.id).eq('active',true).order('calculated_level',{ascending:false,nullsFirst:false}).limit(1);return {count:count.count,depth:depth.data?.[0]?.calculated_level??0};}));
 const href=admin?'/admin/boms':'/boms';const paging=(p:number)=>`${href}?${new URLSearchParams({q,state,page:String(p)})}`;
 return <><div className="page-heading"><div><p className="eyebrow">{admin?'ADMINISTRACIÓN / GESTIÓN':'CONSULTA / INGENIERÍA'}</p><h1>{admin?'Gestión de BOM':'Explorador BOM'}</h1><p>{admin?'Crea, edita, importa y conserva el historial de tus diseños.':'Busca un diseño y consulta su estructura, imagen y materiales vinculados.'}</p></div>{admin&&<Link className="button primary" href="/admin/boms/new">+ Nuevo BOM</Link>}</div>{admin&&<section className="panel filters"><Link href="/admin/boms/import">Importar Excel</Link><Link href="/api/engineering/excel?template=1">Descargar plantilla Excel</Link><Link href="/api/engineering/excel">Exportar todos los BOM</Link></section>}<form className="filters panel"><label>Buscar diseño, modelo o código<input name="q" defaultValue={q} placeholder="Ej.: Pocket"/></label><label>Estado<select name="state" defaultValue={state}><option value="ACTIVE">Activos</option><option value="INACTIVE">Inactivos</option><option value="ARCHIVED">Archivados</option><option value="ALL">Todos</option></select></label><button className="primary">Buscar BOM</button></form><p>{matches.length} BOM encontrados · página {current}</p><div className="bom-directory">{visible.map((b,i)=>{const m=b.product_skus.product_models;const image=m.image_path??b.product_skus.image_path;return <article className="panel" key={b.id}>{image?<img className="bom-thumbnail" src={`/api/engineering/image?path=${encodeURIComponent(image)}`} alt={m.catalog_name_original}/>:<div className="image-placeholder">Imagen no informada</div>}<h2>{m.catalog_name_original}</h2><p>{m.reference_code??b.product_skus.sap_material_code??'Código no informado'} · Versión {b.version}</p><p>{stats[i].count??'—'} componentes · {stats[i].depth} niveles · {b.lifecycle}</p><div className="filters"><Link href={`/boms/${b.id}`}>Ver</Link>{admin&&<><Link href={`/admin/boms/${b.id}`}>Editar / Archivar</Link><Link href={`/admin/boms/new?duplicate=${b.id}`}>Duplicar</Link><Link href={`/api/engineering/excel?id=${b.id}`}>Exportar / usar como plantilla</Link></>}</div></article>;})}</div>{!matches.length&&<p className="empty-state">No se encontraron BOM para esta búsqueda.</p>}<div className="filters">{current>1&&<Link href={paging(current-1)}>← Anterior</Link>}{current*20<matches.length&&<Link href={paging(current+1)}>Siguiente →</Link>}</div></>;
}
