'use client';
import { useState } from 'react';
import Link from 'next/link';
import { BomExplorer } from './bom-explorer';
import { graphNodes,validateEngineering,type EngineeringBom } from '@/lib/engineering';
export function EngineeringView({bom,canEdit,sap,history}:{bom:EngineeringBom;canEdit:boolean;sap:any[];history:any[]}){
 const [tab,setTab]=useState('Ingeniería');const [selected,setSelected]=useState('');const report=validateEngineering(bom);const header=sap.find(h=>String(h.id)===selected);
 return <><Link href="/boms">← Buscar otro diseño</Link><div className="page-heading"><div><p className="eyebrow">EXPLORADOR BOM / CONSULTA</p><h1>{bom.design}</h1><p>{bom.referenceCode??'Código no informado'} · Revisión {bom.revision} · {bom.lifecycle==='ACTIVE'?'Activo':bom.lifecycle==='ARCHIVED'?'Archivado':'Inactivo'}</p></div>{canEdit&&<Link className="button" href={`/admin/boms/${bom.id}`}>Editar BOM</Link>}</div><section className="panel bom-design-header">{bom.imagePath?<img src={`/api/engineering/image?path=${encodeURIComponent(bom.imagePath)}`} alt={bom.design}/>:<div className="image-placeholder">Imagen no informada</div>}<div><h2>{bom.design}</h2><p>{bom.description??'Descripción no informada'}</p><p>{bom.brand&&`Marca: ${bom.brand} · `}{bom.nodes.filter(n=>n.active).length} componentes activos · {Math.max(0,...Object.values(report.levels))} niveles</p><span className="badge">{report.valid?'Sin errores críticos':'Requiere revisión'}</span></div></section>
 <div className="tabs" role="tablist">{['Ingeniería','BOM SAP','Reconciliación','Fuentes y validaciones'].map(t=><button key={t} role="tab" aria-selected={tab===t} className={tab===t?'active':''} onClick={()=>setTab(t)}>{t}</button>)}</div>
 {tab==='Ingeniería'&&<BomExplorer key={`${bom.id}-${bom.revision}`} title={bom.design} items={graphNodes(bom)}/>}
 {tab==='BOM SAP'&&<section className="panel"><h2>Lista SAP vinculada al SKU</h2><p>La lista SAP se conserva separada del árbol de ingeniería.</p><label>Centro y alternativa<select value={selected} onChange={e=>setSelected(e.target.value)}><option value="">Seleccionar BOM SAP</option>{sap.map(h=><option key={h.id} value={h.id}>{h.center} · alternativa {h.alternative} · base {h.base_quantity} {h.base_unit}</option>)}</select></label>{!sap.length&&<p>No hay una lista SAP vinculada a este diseño.</p>}{header&&<div className="table-scroll"><table><thead><tr><th>Posición</th><th>Material</th><th>Descripción</th><th>Cantidad</th><th>Unidad</th><th>Consumo unitario</th></tr></thead><tbody>{header.items.map((i:any)=><tr key={i.id}><td>{i.position}</td><td>{i.component_code}</td><td>{i.component_description}</td><td>{i.component_quantity}</td><td>{i.component_unit}</td><td>{i.normalized_unit_quantity}</td></tr>)}</tbody></table></div>}</section>}
 {tab==='Reconciliación'&&<section className="panel"><h2>Identidad y relaciones</h2><p>Este árbol pertenece exclusivamente a {bom.design}. Los padres se resuelven dentro del mismo BOM; el nivel declarado se conserva y se compara con el calculado.</p><p>Código de referencia: {bom.referenceCode??'No informado'}. Un código de referencia no crea una asociación automática con SAP.</p><p>{sap.length} listas SAP vinculadas al SKU. {bom.nodes.filter(n=>n.externalId).length} componentes conservan códigos históricos.</p>{bom.sourceType==='LEGACY_IMPORT'&&bom.nodes.some(n=>n.externalId==='1')&&bom.referenceCode==='3C83010'&&<figure className="source-reference"><img src="/api/pilot-reference" alt="Diagrama original de Pocket Boreal" width="691" height="434"/><figcaption>Documento original del caso Pocket Boreal.</figcaption></figure>}</section>}
 {tab==='Fuentes y validaciones'&&<section className="panel"><h2>Origen y revisiones</h2><p>Fuente: {bom.sourceType==='MANUAL'?'Editor administrativo':bom.sourceType==='EXCEL_IMPORT'?'Importación Excel':'Importación histórica'} · {bom.sourceFile??'Archivo no informado'}</p><p>{report.issues.filter(i=>i.severity==='ERROR').length} errores · {report.issues.filter(i=>i.severity==='WARNING').length} advertencias</p>{report.issues.map((i,k)=><p className={`alert ${i.severity==='ERROR'?'error':''}`} key={k}>{i.node?`${bom.nodes[i.node-1]?.name}: `:''}{i.message}</p>)}<h3>Historial de guardado</h3>{history.length?<ul>{history.map(h=><li key={h.revision}>Revisión {h.revision} · {new Date(h.recorded_at).toLocaleString('es-CO')} · usuario registrado en auditoría</li>)}</ul>:<p>Datos anteriores al editor administrativo; se conservarán al realizar la primera modificación.</p>}</section>}</>;
}
