'use client';
import { useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { BomExplorer } from './bom-explorer';
import { graphNodes,validateEngineering,visibleNotes,editNotes,type EngineeringBom,type EngineeringNode } from '@/lib/engineering';
export function EngineeringEditor({initial}:{initial:EngineeringBom}){
 const [bom,setBom]=useState(initial);const [selected,setSelected]=useState<string|null>(initial.nodes[0]?.key??null);const [step,setStep]=useState(initial.nodes.length?2:1);
 const [preview,setPreview]=useState(false);const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const router=useRouter();
 const validation=validateEngineering(bom);const node=bom.nodes.find(n=>n.key===selected);
 const update=(patch:Partial<EngineeringBom>)=>{setBom(b=>({...b,...patch}));setAck(false);setMessage('');};
 function editNode(patch:Partial<EngineeringNode>){update({nodes:bom.nodes.map(n=>n.key===selected?{...n,...patch}:n)});}
 function add(parentKey:string|null){const key=crypto.randomUUID();const p=bom.nodes.find(n=>n.key===parentKey);update({nodes:[...bom.nodes,{key,parentKey,externalId:null,name:'',declaredLevel:parentKey?(p?.declaredLevel??0)+1:1,quantity:null,unit:null,leadTime:null,leadTimeUnit:null,notes:null,active:true,sequence:Math.max(0,...bom.nodes.map(n=>n.sequence))+1,sourceFile:null,sourceRow:null}]});setSelected(key);}
 function deactivate(subtree=false){if(!node)return;const children=bom.nodes.filter(n=>n.parentKey===node.key&&n.active);if(children.length&&!subtree){setMessage(`No se puede quitar ${node.name}: contiene ${children.length} hijos activos. Reasigna sus padres o desactiva la estructura dependiente.`);return;}const keys=new Set([node.key]);if(subtree){if(!window.confirm('Se desactivará este componente y todos sus descendientes. Se conservará el historial.'))return;let change=true;while(change){change=false;for(const n of bom.nodes)if(n.parentKey&&keys.has(n.parentKey)&&!keys.has(n.key)){keys.add(n.key);change=true;}}}update({nodes:bom.nodes.map(n=>keys.has(n.key)?{...n,active:false}:n)});}
 async function save(){setBusy(true);setMessage('');try{const r=await fetch('/api/engineering',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({boms:[{...bom,sourceType:'MANUAL'}],acknowledged:ack})});const j=await r.json();if(!r.ok)throw new Error(j.error);const saved=j.saved[0];setBom(b=>({...b,...saved}));setMessage('BOM guardado correctamente.');router.replace(`/admin/boms/${saved.id}?saved=1`);router.refresh();}catch(e){setMessage(e instanceof Error?e.message:'No se pudo guardar.');}finally{setBusy(false);}}
 async function upload(file?:File){if(!file)return;setBusy(true);try{const form=new FormData();form.set('file',file);const r=await fetch('/api/engineering/image',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.error);update({imagePath:j.path});}catch(e){setMessage(e instanceof Error?e.message:'Error de imagen.');}finally{setBusy(false);}}
 return <><div className="page-heading"><div><p className="eyebrow">ADMINISTRACIÓN / GESTIÓN DE BOM</p><h1>{bom.id?'Editar BOM':'Nuevo BOM'}</h1><p>Define el diseño, construye su estructura y revisa el árbol antes de guardar.</p></div><Link href="/admin/boms">Volver a gestión</Link></div>
 <div className="tabs"><button className={step===1?'active':''} onClick={()=>setStep(1)}>1. Modelo e imagen</button><button className={step===2?'active':''} onClick={()=>setStep(2)}>2. Estructura y validación</button></div>
 {step===1&&<section className="panel"><div className="bom-form-grid"><label>Diseño *<input value={bom.design} onChange={e=>update({design:e.target.value})} required/></label><label>Código de referencia, si existe<input value={bom.referenceCode??''} onChange={e=>update({referenceCode:e.target.value||null})}/></label><label>Marca<input value={bom.brand??''} onChange={e=>update({brand:e.target.value||null})}/></label><label>Estado<select value={bom.lifecycle} onChange={e=>update({lifecycle:e.target.value as EngineeringBom['lifecycle']})}><option value="ACTIVE">Activo</option><option value="INACTIVE">Inactivo</option><option value="ARCHIVED">Archivado</option></select></label><label>Descripción<textarea value={bom.description??''} onChange={e=>update({description:e.target.value||null})}/></label><label>Observaciones del modelo<textarea value={bom.notes??''} onChange={e=>update({notes:e.target.value||null})}/></label></div><label>Imagen del colchón (PNG, JPEG o WebP · máximo 5 MB)<input type="file" accept="image/png,image/jpeg,image/webp" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label>{bom.imagePath&&<div className="bom-model-image"><img src={`/api/engineering/image?path=${encodeURIComponent(bom.imagePath)}`} alt={bom.design}/><button onClick={()=>update({imagePath:null})}>Quitar imagen del modelo</button></div>}<p className="footnote">Al cambiar o quitar una imagen, se conserva el archivo anterior para el historial.</p><button className="primary" disabled={!bom.design.trim()} onClick={()=>setStep(2)}>Siguiente: construir estructura</button></section>}
 {step===2&&<><section className="panel"><div className="section-heading"><div><h2>{bom.design||'Diseño sin nombre'}</h2><p>{bom.nodes.filter(n=>n.active).length} componentes activos · {bom.nodes.filter(n=>!n.active).length} inactivos</p></div><button onClick={()=>add(null)}>+ Agregar componente</button></div><div className="bom-editor-grid"><div><label>Seleccionar componente<select size={Math.min(12,Math.max(3,bom.nodes.length))} value={selected??''} onChange={e=>setSelected(e.target.value)}>{bom.nodes.map((n,i)=><option key={n.key} value={n.key}>{n.active?'':'[Inactivo] '}{n.name||`Componente sin nombre ${i+1}`} · N{n.declaredLevel??'—'}</option>)}</select></label></div>{node?<div><div className="bom-form-grid"><label>Nombre del componente *<input value={node.name} onChange={e=>editNode({name:e.target.value})}/></label><label>Padre<select value={node.parentKey??''} onChange={e=>editNode({parentKey:e.target.value||null})}><option value="">Producto terminado</option>{bom.nodes.filter(n=>n.key!==node.key).map((n,i)=><option key={n.key} value={n.key}>{n.name||`Sin nombre ${i+1}`}{n.active?'':' (inactivo)'}</option>)}</select></label><label>Nivel declarado<input type="number" min="1" step="1" value={node.declaredLevel??''} onChange={e=>editNode({declaredLevel:e.target.value===''?null:Number(e.target.value)})}/></label><label>Cantidad *<input type="number" min="0.000001" step="any" value={node.quantity??''} onChange={e=>editNode({quantity:e.target.value===''?null:Number(e.target.value)})}/></label><label>Lead time<input type="number" min="0" step="any" value={node.leadTime??''} onChange={e=>editNode({leadTime:e.target.value===''?null:Number(e.target.value)})}/></label><label>Unidad temporal, si se conoce<input value={node.leadTimeUnit??''} placeholder="No informada" onChange={e=>editNode({leadTimeUnit:e.target.value||null})}/></label><label>Unidad de cantidad, si se conoce<input value={node.unit??''} placeholder="No informada" onChange={e=>editNode({unit:e.target.value||null})}/></label><label>Observaciones<textarea value={visibleNotes(node.notes)??''} onChange={e=>editNode({notes:editNotes(node.notes,e.target.value)})}/></label></div>{node.externalId&&<p className="footnote">Código histórico: {node.externalId}</p>}<div className="filters"><button disabled={!node.active} onClick={()=>add(node.key)}>+ Agregar hijo</button>{node.active?<><button onClick={()=>deactivate()}>Desactivar componente</button><button onClick={()=>deactivate(true)}>Desactivar con descendientes</button></>:<button onClick={()=>editNode({active:true})}>Reactivar componente</button>}</div></div>:<p>Agrega el primer componente para comenzar.</p>}</div></section>
 <section className="panel"><h2>Validación</h2><p>{validation.issues.filter(i=>i.severity==='ERROR').length} errores · {validation.issues.filter(i=>i.severity==='WARNING').length} advertencias</p><details><summary>Ver observaciones de la estructura</summary>{validation.issues.map((i,k)=><p className={`alert ${i.severity==='ERROR'?'error':''}`} key={k}>{i.node?`${bom.nodes[i.node-1]?.name||'Componente'}: `:''}{i.message}</p>)}</details><div className="filters"><button disabled={!validation.valid} onClick={()=>setPreview(!preview)}>{preview?'Ocultar previsualización':'Previsualizar árbol'}</button><label className="inline-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>He revisado la estructura y acepto las advertencias.</label><button className="primary" disabled={busy||!validation.valid||(!ack&&validation.issues.some(i=>i.severity==='WARNING'))} onClick={save}>{busy?'Guardando…':bom.id?'Guardar cambios':'Guardar BOM'}</button></div></section>{preview&&validation.valid&&<BomExplorer key={`${bom.id}-${bom.revision}`} items={graphNodes(bom)} title={bom.design}/>}</>}
 {message&&<p className="alert" role="status">{message}</p>}{bom.id&&<Link className="button" href={`/boms/${bom.id}`}>Ver en Explorador BOM →</Link>}</>;
}
