'use client';
import { useState } from 'react';
import Link from 'next/link';
import { BomExplorer } from './bom-explorer';
import { graphNodes,type EngineeringBom } from '@/lib/engineering';
export function EngineeringImport(){
 const [file,setFile]=useState<File|null>(null);const [result,setResult]=useState<any>(null);const [mode,setMode]=useState('update');const [selected,setSelected]=useState(0);const [ack,setAck]=useState(false);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [saved,setSaved]=useState<{id:number}[]>([]);
 async function submit(phase:string){if(!file)return;setBusy(true);setMessage('');try{const form=new FormData();form.set('file',file);form.set('mode',mode);form.set('phase',phase);if(phase==='save'){form.set('hash',result.hash);form.set('expected',JSON.stringify(result.boms.map((b:EngineeringBom)=>({id:b.id,revision:b.revision}))));form.set('acknowledged',String(ack));}const r=await fetch('/api/engineering/excel',{method:'POST',body:form});const j=await r.json();if(!r.ok)throw new Error(j.error);if(phase==='save'){setSaved(j.saved);setResult(null);setMessage('BOM guardados correctamente. Ya están disponibles en el Explorador.');}else{setResult(j);setSelected(0);setAck(false);setSaved([]);}}catch(e){setMessage(e instanceof Error?e.message:'No se pudo procesar el Excel.');}finally{setBusy(false);}}
 const b=result?.boms[selected] as EngineeringBom|undefined;
 return <><p className="eyebrow">ADMINISTRACIÓN / IMPORTACIÓN EXCEL</p><h1>Importar uno o varios BOM</h1><section className="panel"><p>Usa el mismo formato para carga individual y masiva. La confirmación guarda todos los BOM de la carga en una sola transacción.</p><div className="filters"><Link href="/api/engineering/excel?template=1">Descargar plantilla Excel</Link><Link href="/admin/boms">Volver a gestión</Link></div><label>Archivo Excel<input type="file" accept=".xlsx" onChange={e=>{setFile(e.target.files?.[0]??null);setResult(null);setSaved([]);}}/></label><label>Al encontrar una referencia existente<select value={mode} onChange={e=>{setMode(e.target.value);setResult(null);}}><option value="update">Actualizar si también coincide el diseño; crear los nuevos</option><option value="copy">Crear copias independientes de todos</option></select></label><button className="primary" disabled={!file||busy} onClick={()=>submit('preview')}>{busy?'Procesando…':'Leer y validar Excel'}</button></section>
 {result&&<><section className="panel"><h2>{file?.name}</h2><p>{result.summary.designs} diseños · {result.summary.boms} BOM · {result.summary.nodes} componentes · {result.summary.errors} errores · {result.summary.warnings} advertencias</p>{result.errors.map((e:string,i:number)=><p className="alert error" key={i}>{e}</p>)}<label>Previsualizar diseño<select value={selected} onChange={e=>setSelected(Number(e.target.value))}>{result.boms.map((bom:EngineeringBom,i:number)=><option key={i} value={i}>{bom.design} · {bom.id?'Actualizar existente':'Crear nuevo'}</option>)}</select></label><details><summary>Validaciones del BOM seleccionado</summary>{result.validation[selected]?.issues.map((i:any,k:number)=><p className={`alert ${i.severity==='ERROR'?'error':''}`} key={k}>{i.message}</p>)}</details><label className="inline-check"><input type="checkbox" checked={ack} onChange={e=>setAck(e.target.checked)}/>Confirmo la revisión de los diseños y advertencias.</label><button className="primary" disabled={busy||!ack||result.summary.errors>0} onClick={()=>submit('save')}>Confirmar y guardar la carga</button></section>{b&&result.validation[selected]?.valid&&<BomExplorer key={selected} title={b.design} items={graphNodes(b)}/>}</>}
 {message&&<p role="status" className="alert">{message}</p>}{saved.map((s,i)=><p key={s.id}><Link href={`/boms/${s.id}`}>Abrir BOM guardado {i+1} →</Link></p>)}</>;
}
