'use client';
import { useState } from 'react';
import { useRouter } from 'next/navigation';
import Link from 'next/link';
import type { MrpProduct,MrpHeader,MrpInput,MrpResult } from '@/lib/mrp';
const fmt=(n:number|null)=>n===null?'—':new Intl.NumberFormat('es-CO',{maximumFractionDigits:8}).format(n);
const tabs=['Plan de producción','Requerimientos','Materiales compartidos','Validaciones'];
export function MrpPlanner({products,headers,canCalculate,initial}:{products:MrpProduct[];headers:MrpHeader[];canCalculate:boolean;initial:any}){
 const router=useRouter();
 const [plan,setPlan]=useState<MrpInput[]>(initial?.input??[{productId:0,headerId:null,quantity:1}]),[result,setResult]=useState<MrpResult|null>(initial?.result??null),[run,setRun]=useState<string|null>(initial?.id??null),[tab,setTab]=useState(initial?1:0),[busy,setBusy]=useState(false),[error,setError]=useState(''),[filter,setFilter]=useState(''),[family,setFamily]=useState(''),[classification,setClassification]=useState(''),[search,setSearch]=useState('');
 function update(i:number,patch:Partial<MrpInput>){setPlan(plan.map((p,j)=>i===j?{...p,...patch}:p));setResult(null);setRun(null);}
 async function calculate(){setBusy(true);setError('');try{const res=await fetch('/api/mrp',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({plan})});const data=await res.json();if(!res.ok)throw new Error(data.error);setResult(data.result);setRun(data.id);setTab(1);router.refresh();}catch(e){setError(e instanceof Error?e.message:'No se pudo calcular.');}finally{setBusy(false);}}
 const productCodes=new Set(products.map(p=>p.code).filter(Boolean));const missing=products.filter(p=>!p.code||!headers.some(h=>h.code===p.code));const orphan=headers.filter(h=>!productCodes.has(h.code));
 const rows=result?.rows.filter(r=>(tab!==2||r.consumers>1)&&(!family||r.family===family)&&(!classification||r.classification===classification)&&`${r.code} ${r.description}`.toLowerCase().includes(filter.toLowerCase()))??[];
 return <><div className="tabs" role="tablist">{tabs.map((t,i)=><button key={t} role="tab" aria-selected={tab===i} className={tab===i?'active':''} onClick={()=>setTab(i)}>{t}</button>)}</div>{error&&<p role="alert" className="alert error">{error}</p>}
 {tab===0&&<section className="panel"><div className="section-heading"><h2>Plan de producción</h2><Link href="/material-lists/links">Revisar relaciones SAP →</Link></div><label>Buscar productos para seleccionar<input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Código o nombre"/></label><div className="table-scroll mrp-plan"><table><thead><tr><th>Producto</th><th>Centro · alternativa · base</th><th>Cantidad a producir</th><th/></tr></thead><tbody>{plan.map((line,i)=><tr key={i}><td><select aria-label={`Producto ${i+1}`} disabled={busy||!canCalculate} value={line.productId} onChange={e=>update(i,{productId:Number(e.target.value),headerId:null})}><option value={0}>Selecciona un producto</option>{products.filter(p=>p.id===line.productId||`${p.code} ${p.name}`.toLowerCase().includes(search.toLowerCase())).map(p=><option key={p.id} value={p.id}>{p.code??'Sin SAP'} · {p.name}</option>)}</select></td><td><select aria-label={`Lista SAP ${i+1}`} disabled={busy||!canCalculate} value={line.headerId??''} onChange={e=>update(i,{headerId:Number(e.target.value)||null})}><option value="">Elegir lista SAP</option>{headers.filter(h=>h.code===products.find(p=>p.id===line.productId)?.code).map(h=><option key={h.id} value={h.id}>{h.center} · Alt. {h.alternative} · {h.base} {h.unit}</option>)}</select></td><td><input aria-label={`Cantidad ${i+1}`} type="number" min="0.000001" max="1000000000" step="any" disabled={busy||!canCalculate} value={line.quantity} onChange={e=>update(i,{quantity:Number(e.target.value)})}/></td><td><button aria-label={`Quitar producto ${i+1}`} disabled={busy||!canCalculate||plan.length===1} onClick={()=>{setPlan(plan.filter((_,j)=>i!==j));setResult(null);setRun(null);}}>Quitar</button></td></tr>)}</tbody></table></div><div className="filters"><button disabled={busy||!canCalculate||plan.length>=100} onClick={()=>{setPlan([...plan,{productId:0,headerId:null,quantity:1}]);setResult(null);setRun(null);}}>+ Agregar producto</button><button className="primary" disabled={busy||!canCalculate} onClick={calculate}>{busy?'Calculando y guardando…':'Calcular MRP'}</button></div><p>Cada producto usa una sola lista seleccionada. La familia y la clasificación no excluyen consumos.</p>{!canCalculate&&<p className="alert">Tu rol permite consultar las ejecuciones guardadas.</p>}</section>}
 {result&&tab!==0&&<><div className="metrics compact"><div><span>Productos programados</span><strong>{result.summary.products}</strong><small>{Object.entries(result.summary.plannedByUnit).map(([u,n])=>`${fmt(n)} ${u}`).join(' · ')}</small></div><div><span>Materiales requeridos</span><strong>{result.summary.materials}</strong><small>{result.summary.families} familias clasificadas</small></div><div><span>Materiales compartidos</span><strong>{result.summary.shared}</strong></div><div><span>Alertas</span><strong>{result.alerts.length}</strong><small>{result.status==='INCOMPLETE'?'Resultado incompleto':result.status==='READY'?'Validado':'Revisar advertencias'}</small></div></div><p className="footnote">{result.scope} · Ejecución <Link href={`/mrp?run=${run}`}>{run}</Link></p></>}
 {(tab===1||tab===2)&&(!result?<div className="empty-state">Programa productos y calcula su requerimiento, o abre una ejecución guardada.</div>:<section className="panel"><h2>{tabs[tab]}</h2><div className="filters"><label>Código o material<input value={filter} onChange={e=>setFilter(e.target.value)}/></label><label>Familia<select value={family} onChange={e=>setFamily(e.target.value)}><option value="">Todas</option>{[...new Set(result.rows.map(r=>r.family).filter(Boolean))].map(f=><option key={f} value={f!}>{f}</option>)}</select></label><label>Clasificación<select value={classification} onChange={e=>setClassification(e.target.value)}><option value="">Todas</option>{[...new Set(result.rows.map(r=>r.classification).filter(Boolean))].map(c=><option key={c} value={c!}>{c}</option>)}</select></label></div><p className="footnote">Los filtros solo cambian esta vista. {rows.length} filas visibles; se conserva el cálculo completo.</p><div className="table-scroll mrp-results"><table><thead><tr><th>Código / material</th><th>Familia / clasificación</th><th>Requerimiento bruto</th><th>Modelos</th><th>Compra sugerida</th><th>Origen</th></tr></thead><tbody>{rows.map(r=><tr key={`${r.code}:${r.unit}`}><td><Link href={`/materials?q=${encodeURIComponent(r.code)}`}>{r.code}</Link><br/>{r.description}</td><td>{r.family??'Sin familia'}<br/>{r.classification??'Sin clasificación'}</td><td className="number"><strong>{fmt(r.gross)} {r.unit}</strong>{r.negative<0&&<p className="badge warning">Negativo separado: {fmt(r.negative)} {r.unit}<br/>Requiere clasificación</p>}</td><td>{r.consumers}</td><td>{r.purchaseQuantity===null?r.conversionStatus:<>{fmt(r.purchaseQuantity)} {r.purchaseUnit}<br/>Sugerencia: {r.purchasePacks} empaques</>}</td><td><details><summary>Ver contribuciones ({r.contributions.length})</summary>{r.contributions.map(c=><div className="source-row" key={`${c.productId}:${c.itemId}`}><strong>{c.productName}</strong><p>{fmt(c.original)} ÷ {fmt(c.base)} × {fmt(c.planned)} {c.plannedUnit} = {fmt(c.originalRequirement)} {r.unit}{!c.included?' · Separado del total positivo':''}</p><small>SAP {c.productCode} · centro {c.center} · alternativa {c.alternative} · posición {c.position} · fila Excel {c.sourceRow} · cabecera {c.headerId}</small></div>)}</details></td></tr>)}</tbody></table></div></section>)}
 {tab===3&&<section className="panel"><h2>Validaciones</h2><p><Link href="/material-lists/validation">Validaciones de todo el catálogo SAP →</Link></p>{result?.alerts.map((a,i)=><p key={i} className={`alert ${a.severity==='ERROR'?'error':''}`}><strong>{a.severity==='ERROR'?'ERROR':a.severity==='WARNING'?'ADVERTENCIA':'INFORMACIÓN'}</strong> · {a.message}</p>)}<h3>Relaciones del catálogo actual</h3><p>{missing.length} productos sin lista SAP vinculada · {orphan.length} listas sin producto ERP relacionado.</p><details><summary>Productos pendientes</summary>{missing.map(p=><p key={p.id}>{p.name} · {p.code??'Sin código SAP'}</p>)}</details><details><summary>Listas sin producto ERP</summary>{orphan.map(h=><p key={h.id}>{h.code} · {h.center} · Alt. {h.alternative}</p>)}</details><p><Link href="/material-lists/links">Revisar relaciones</Link> · <Link href="/materials/catalogs">Confirmar unidades y familias</Link></p></section>}</>;
}



