'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { useState } from 'react';
import { LayoutDashboard, Package, GitBranch, Layers, ShieldCheck, Upload, Settings, Menu, LogOut, TrendingUp, Gauge, GraduationCap, DollarSign, Warehouse, Timer, CalendarRange, QrCode } from 'lucide-react';
import { logout } from '@/app/login/actions';
const links = [ ['/', 'Vista general', LayoutDashboard], ['/products', 'Productos', Package], ['/boms', 'Explorador BOM', GitBranch], ['/material-lists', 'Listas / Requerimiento', Layers], ['/materials', 'Materiales / Where-used', Layers], ['/mrp', 'MRP', Layers], ['/demand', 'Demanda', TrendingUp], ['/restrictions', 'Restricciones', Gauge], ['/training', 'Entrenamiento', GraduationCap], ['/mps', 'Plan maestro', CalendarRange], ['/costs', 'Costos', DollarSign], ['/inventory', 'Inventario', Warehouse], ['/routings', 'Tiempos de producción', Timer],['/quality', 'Calidad de datos', ShieldCheck], ['/imports', 'Importar datos', Upload], ['/settings', 'Estado del sistema', Settings] ] as const;
export function Shell({ children, name, role, qr }: { children: React.ReactNode; name: string; role: string; qr?: boolean }) {
  const path = usePathname(); const [open, setOpen] = useState(false);
  return <div className="app-shell"><button className="menu-toggle" onClick={() => setOpen(!open)} aria-label="Mostrar navegación"><Menu size={22}/></button><aside className={`sidebar ${open ? 'open' : ''}`}><Link className="wordmark" href="/">LAMITEX<span>PLANNING ERP</span></Link><div className="line-label">LÍNEA RESORPEDIC</div><nav>{links.map(([href, label, Icon]) => <Link href={href} key={href} onClick={() => setOpen(false)} className={(href === '/' ? path === '/' : path.startsWith(href)) ? 'active' : ''}><Icon size={18}/>{label}</Link>)}{['ADMIN','ENGINEERING'].includes(role)&&<Link href="/admin/boms" onClick={()=>setOpen(false)} className={path.startsWith('/admin/boms')?'active':''}><Settings size={18}/>Gestión de BOM</Link>}{qr&&<Link href="/control" onClick={()=>setOpen(false)}><QrCode size={18}/>Control de colchones (QR)</Link>}</nav><div className="future"><span>PRÓXIMAS ETAPAS</span><p>Inventario <small>En desarrollo</small></p></div><div className="sidebar-user"><strong>{name}</strong><small>{role}</small><form action={logout}><button><LogOut size={16}/> Cerrar sesión</button></form></div></aside><div className="workspace"><header className="topbar"><span>Planificación industrial <b>/</b> Resorpedic</span><span className="status-dot">Sesión activa</span></header><main className="main-content">{children}</main><footer>LAMITEX · Ingeniería, trazabilidad y planificación</footer></div></div>;
}

