import Link from 'next/link';
import { requireUser } from '@/lib/auth';
const fmt=(n:number|null)=>n===null?'—':new Intl.NumberFormat('es-CO',{maximumFractionDigits:8}).format(n);
export default async function Page({searchParams}:{searchParams:Promise<{q?:string;header?:string;bom?:string;quantity?:string;page?:string}>}){
 const {db,profile}=await requireUser();const p=await searchParams;const q=(p.q??'').replace(/[%_,()]/g,'').slice(0,100);const page=Math.max(1,Math.min(100000,parseInt(p.page??'1')||1));
 let query=db.from('sap_bom_headers').select('*',{count:'exact'}).eq('active',true).order('parent_material_code').order('center').order('alternative').range((page-1)*30,page*30-1);if(q)query=query.or(`parent_material_code.ilike.%${q}%,parent_description.ilike.%${q}%,center.ilike.%${q}%`);
 const [lists,latest]=await Promise.all([query,db.from('imports').select('id,file_name,file_hash,imported_at,total_rows').eq('import_type','SAP_MATERIALS').eq('status','COMPLETED').order('id',{ascending:false}).limit(1)]);if(lists.error)throw new Error(lists.error.message);
 let selected:any=null;if(p.header){const r=await db.from('sap_bom_headers').select('*').eq('id',p.header).maybeSingle();if(r.error)throw new Error(r.error.message);selected=r.data;}else if(p.bom){try{const [center,code,alt]=JSON.parse(p.bom);const r=await db.from('sap_bom_headers').select('*').eq('center',center).eq('parent_material_code',code).eq('alternative',alt).eq('active',true).maybeSingle();selected=r.data;}catch{/* Invalid legacy selector displays directory. */}}
 const items:any[]=[];if(selected){for(let o=0;;o+=1000){const r=await db.from('sap_bom_items').select('*').eq('sap_bom_header_id',selected.id).order('source_row').range(o,o+999);if(r.error)throw new Error(r.error.message);items.push(...r.data);if(r.data.length<1000)break;}}
 const planned=Number(p.quantity??1);const ready=selected&&selected.base_quantity>0&&selected.base_unit&&Number.isFinite(planned)&&planned>=0&&planned<=1e9;
 return <><p className="eyebrow">POSTGRESQL / BOM DE MATERIALES</p><h1>Listas SAP y requerimiento directo</h1><p className="muted">Cada centro y alternativa conserva sus cantidades y unidades originales.</p><div className="filters"><Link className="button primary" href="/mrp">Calcular MRP consolidado</Link><Link className="button" href="/material-lists/links">Relaciones producto ↔ SAP</Link>{['ADMIN','ENGINEERING'].includes(profile.role)&&<Link className="button" href="/material-lists/import">Actualizar Excel SAP</Link>}</div>
 {latest.data?.[0]&&<details className="panel"><summary>Última fuente importada · {latest.data[0].total_rows} posiciones</summary><p>{latest.data[0].file_name} · {latest.data[0].imported_at}</p><code className="footnote">{latest.data[0].file_hash}</code></details>}
 <section className="panel"><h2>Buscar y elegir una lista</h2><form className="filters"><label>Material, descripción o centro<input name="q" defaultValue={q}/></label><button className="primary">Buscar listas</button></form><p>{lists.count} listas activas · página {page}</p><div className="table-scroll"><table><thead><tr><th>Material padre</th><th>Descripción</th><th>Centro</th><th>Alternativa</th><th>Base</th><th/></tr></thead><tbody>{lists.data.map(h=><tr key={h.id}><td>{h.parent_material_code}{h.parent_material_code!==h.parent_material_code.trim()&&<span className="badge warning">Código con espacios</span>}</td><td>{h.parent_description}</td><td>{h.center}</td><td>{h.alternative}</td><td>{h.base_quantity} {h.base_unit}</td><td><Link href={`?${new URLSearchParams({q,header:String(h.id),page:String(page)})}`}>Ver materiales</Link></td></tr>)}</tbody></table></div><div className="pagination">{page>1&&<Link href={`?${new URLSearchParams({q,page:String(page-1)})}`}>Anterior</Link>}{(lists.count??0)>page*30&&<Link href={`?${new URLSearchParams({q,page:String(page+1)})}`}>Siguiente</Link>}</div></section>
 {selected&&<section className="panel"><h2>Materiales de {selected.parent_material_code}</h2><p>{selected.parent_description} · Centro {selected.center} · Alternativa {selected.alternative} · Base {selected.base_quantity} {selected.base_unit}</p>{!selected.active&&<p className="alert">Versión histórica; no se selecciona en nuevos cálculos MRP.</p>}<form className="filters"><input type="hidden" name="header" value={selected.id}/><input type="hidden" name="q" value={q}/><label>Cantidad a producir ({selected.base_unit})<input type="number" name="quantity" min="0" max="1000000000" step="any" defaultValue={Number.isFinite(planned)?planned:1}/></label><button className="primary">Calcular requerimiento directo</button></form>{!ready&&<p className="alert error">Revisa la base del BOM y la cantidad programada.</p>}<p className="alert">Consumo unitario = cantidad original ÷ base. Los negativos se conservan por separado y no reducen las necesidades positivas. Revisa cada subensamble en su propia lista y alternativa.</p><div className="table-scroll"><table><thead><tr><th>Pos.</th><th>Componente</th><th>Descripción</th><th>Original</th><th>Consumo unitario</th><th>Requerimiento bruto</th><th>Negativo / revisar</th><th>Alt. componente</th><th>Fuente</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td>{i.position}</td><td><Link href={`/materials/${i.material_id}`}>{i.component_code}</Link><br/><Link href={`/material-lists?q=${encodeURIComponent(i.component_code)}`}>Buscar su lista →</Link></td><td>{i.component_description}</td><td>{fmt(i.component_quantity)} {i.component_unit}</td><td>{ready&&i.component_quantity!==null?fmt(i.component_quantity/selected.base_quantity):'—'} {i.component_unit}</td><td>{ready&&i.component_quantity!==null&&i.component_unit?fmt(Math.max(0,i.component_quantity)/selected.base_quantity*planned):'—'} {i.component_unit}</td><td>{ready&&i.component_quantity<0?`${fmt(i.component_quantity/selected.base_quantity*planned)} ${i.component_unit} · Requiere clasificación`:'—'}</td><td>{i.component_alternative}</td><td>{i.source_sheet??selected.source_sheet??'Data'} · fila {i.source_row}</td></tr>)}</tbody></table></div></section>}</>;
}
