SET local check_function_bodies = off;

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON SEQUENCES FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON FUNCTIONS FROM "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" REVOKE ALL ON TABLES FROM "service_role";

CREATE TABLE "public"."engineering_bom_nodes" (
  "id"                         bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "engineering_bom_id"         bigint                   NOT NULL,
  "legacy_component_id"        integer                  NOT NULL,
  "component_name_original"    text                     NOT NULL,
  "component_name_canonical"   text,
  "parent_legacy_component_id" integer,
  "declared_level"             integer,
  "calculated_level"           integer,
  "quantity"                   numeric(18,6)            NOT NULL DEFAULT 1,
  "unit"                       text                     NOT NULL DEFAULT 'UN'::text,
  "lead_time"                  numeric(18,6),
  "node_type"                  text,
  "sequence_order"             integer,
  "validation_status"          text                     NOT NULL DEFAULT 'PENDING'::text,
  "notes"                      text,
  "source_file"                text,
  "source_row"                 integer,
  "created_at"                 timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"                 timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "engineering_bom_nodes_calculated_level_check" CHECK (((calculated_level IS NULL) OR (calculated_level >= 1))),
  CONSTRAINT "engineering_bom_nodes_check" CHECK (((parent_legacy_component_id IS NULL) OR (parent_legacy_component_id <> legacy_component_id))),
  CONSTRAINT "engineering_bom_nodes_declared_level_check" CHECK (((declared_level IS NULL) OR (declared_level >= 1))),
  CONSTRAINT "engineering_bom_nodes_engineering_bom_id_legacy_component_i_key" UNIQUE (engineering_bom_id, legacy_component_id),
  CONSTRAINT "engineering_bom_nodes_lead_time_check" CHECK (((lead_time IS NULL) OR (lead_time >= (0)::numeric))),
  CONSTRAINT "engineering_bom_nodes_pkey" PRIMARY KEY (id),
  CONSTRAINT "engineering_bom_nodes_quantity_check" CHECK ((quantity > (0)::numeric))
);

ALTER TABLE "public"."engineering_bom_nodes"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."engineering_boms" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_sku_id" bigint                   NOT NULL,
  "version"        integer                  NOT NULL DEFAULT 1,
  "status"         text                     NOT NULL DEFAULT 'DRAFT'::text,
  "description"    text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "approved_at"    timestamp with time zone,
  "approved_by"    text,
  "source_file"    text,
  CONSTRAINT "engineering_boms_pkey" PRIMARY KEY (id),
  CONSTRAINT "engineering_boms_product_sku_id_version_key" UNIQUE (product_sku_id, VERSION)
);

ALTER TABLE "public"."engineering_boms"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."imports" (
  "id"            bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "import_type"   text                     NOT NULL,
  "file_name"     text                     NOT NULL,
  "file_hash"     text,
  "source_system" text,
  "imported_at"   timestamp with time zone NOT NULL DEFAULT now(),
  "imported_by"   text,
  "total_rows"    integer,
  "valid_rows"    integer,
  "warning_rows"  integer,
  "error_rows"    integer,
  "status"        text                     NOT NULL DEFAULT 'PENDING'::text,
  "notes"         text,
  CONSTRAINT "imports_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."imports"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."material_families" (
  "id"             bigint  GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "family_name"    text    NOT NULL,
  "subfamily_name" text,
  "description"    text,
  "active"         boolean NOT NULL DEFAULT true,
  CONSTRAINT "material_families_family_name_subfamily_name_key" UNIQUE (family_name, subfamily_name),
  CONSTRAINT "material_families_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."material_families"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."materials" (
  "id"                       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sap_code"                 text                     NOT NULL,
  "sap_description_original" text,
  "canonical_description"    text,
  "material_family_id"       bigint,
  "base_unit"                text,
  "material_nature"          text,
  "procurement_type"         text,
  "lead_time_days"           numeric(18,6),
  "safety_stock"             numeric(18,6),
  "minimum_lot"              numeric(18,6),
  "image_path"               text,
  "classification_status"    text                     NOT NULL DEFAULT 'UNCLASSIFIED'::text,
  "active"                   boolean                  NOT NULL DEFAULT true,
  "source_file"              text,
  "source_row"               integer,
  "created_at"               timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"               timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "materials_pkey" PRIMARY KEY (id),
  CONSTRAINT "materials_sap_code_key" UNIQUE (sap_code)
);

ALTER TABLE "public"."materials"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_models" (
  "id"                    bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_line"          text                     NOT NULL DEFAULT 'RESORPEDIC'::text,
  "catalog_name_original" text                     NOT NULL,
  "canonical_name"        text,
  "active"                boolean                  NOT NULL DEFAULT true,
  "source_file"           text,
  "source_row"            integer,
  "created_at"            timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"            timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "product_models_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product_models"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."product_skus" (
  "id"                     bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "product_model_id"       bigint                   NOT NULL,
  "commercial_measure"     text,
  "width_cm"               numeric(10,2),
  "length_cm"              numeric(10,2),
  "height_cm"              numeric(10,2),
  "sap_material_code"      text,
  "sap_name_original"      text,
  "legacy_colchon_id"      integer,
  "image_path"             text,
  "reconciliation_status"  text                     NOT NULL DEFAULT 'PENDING_REVIEW'::text,
  "engineering_bom_status" text                     NOT NULL DEFAULT 'PENDING'::text,
  "sap_bom_status"         text                     NOT NULL DEFAULT 'PENDING'::text,
  "active"                 boolean                  NOT NULL DEFAULT true,
  "source_file"            text,
  "source_row"             integer,
  "created_at"             timestamp with time zone NOT NULL DEFAULT now(),
  "updated_at"             timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "product_skus_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."product_skus"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sap_bom_headers" (
  "id"                   bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "import_id"            bigint,
  "product_sku_id"       bigint,
  "center"               text,
  "parent_material_code" text                     NOT NULL,
  "alternative"          text                     NOT NULL DEFAULT '1'::text,
  "base_quantity"        numeric(18,6),
  "base_unit"            text,
  "parent_description"   text,
  "source_file"          text,
  "created_at"           timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "sap_bom_headers_import_id_center_parent_material_code_alter_key" UNIQUE (import_id, center, parent_material_code, alternative),
  CONSTRAINT "sap_bom_headers_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sap_bom_headers"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."sap_bom_items" (
  "id"                       bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "sap_bom_header_id"        bigint                   NOT NULL,
  "position"                 text,
  "component_code"           text                     NOT NULL,
  "component_description"    text,
  "component_quantity"       numeric(18,6),
  "component_unit"           text,
  "normalized_unit_quantity" numeric(18,8),
  "movement_nature"          text                     NOT NULL DEFAULT 'TO_REVIEW'::text,
  "material_id"              bigint,
  "source_row"               integer,
  "created_at"               timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT "sap_bom_items_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."sap_bom_items"
  ENABLE ROW LEVEL SECURITY;

CREATE TABLE "public"."validation_issues" (
  "id"             bigint                   GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  "entity_type"    text                     NOT NULL,
  "entity_id"      bigint,
  "issue_type"     text                     NOT NULL,
  "severity"       text                     NOT NULL DEFAULT 'WARNING'::text,
  "message"        text                     NOT NULL,
  "field_name"     text,
  "current_value"  text,
  "expected_value" text,
  "status"         text                     NOT NULL DEFAULT 'OPEN'::text,
  "created_at"     timestamp with time zone NOT NULL DEFAULT now(),
  "reviewed_at"    timestamp with time zone,
  "reviewed_by"    text,
  "review_comment" text,
  CONSTRAINT "validation_issues_pkey" PRIMARY KEY (id)
);

ALTER TABLE "public"."validation_issues"
  ENABLE ROW LEVEL SECURITY;

CREATE OR REPLACE FUNCTION public.rls_auto_enable()
  RETURNS event_trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'pg_catalog'
  AS $function$
DECLARE
  cmd record;
BEGIN
  FOR cmd IN
    SELECT *
    FROM pg_event_trigger_ddl_commands()
    WHERE command_tag IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
      AND object_type IN ('table','partitioned table')
  LOOP
     IF cmd.schema_name IS NOT NULL AND cmd.schema_name IN ('public') AND cmd.schema_name NOT IN ('pg_catalog','information_schema') AND cmd.schema_name NOT LIKE 'pg_toast%' AND cmd.schema_name NOT LIKE 'pg_temp%' THEN
      BEGIN
        EXECUTE format('alter table if exists %s enable row level security', cmd.object_identity);
        RAISE LOG 'rls_auto_enable: enabled RLS on %', cmd.object_identity;
      EXCEPTION
        WHEN OTHERS THEN
          RAISE LOG 'rls_auto_enable: failed to enable RLS on %', cmd.object_identity;
      END;
     ELSE
        RAISE LOG 'rls_auto_enable: skip % (either system schema or not in enforced list: %.)', cmd.object_identity, cmd.schema_name;
     END IF;
  END LOOP;
END;
$function$;

CREATE OR REPLACE FUNCTION public.set_updated_at()
  RETURNS TRIGGER
  LANGUAGE plpgsql
  AS $function$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$function$;

ALTER TABLE "public"."engineering_bom_nodes"
  ADD CONSTRAINT "fk_engineering_parent" FOREIGN KEY (engineering_bom_id, parent_legacy_component_id)
    REFERENCES public.engineering_bom_nodes(engineering_bom_id, legacy_component_id) DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE "public"."engineering_bom_nodes"
  ADD CONSTRAINT "engineering_bom_nodes_engineering_bom_id_fkey" FOREIGN KEY (engineering_bom_id) REFERENCES public.engineering_boms(id) ON DELETE CASCADE;

ALTER TABLE "public"."materials"
  ADD CONSTRAINT "materials_material_family_id_fkey" FOREIGN KEY (material_family_id) REFERENCES public.material_families(id);

ALTER TABLE "public"."engineering_boms"
  ADD CONSTRAINT "engineering_boms_product_sku_id_fkey" FOREIGN KEY (product_sku_id) REFERENCES public.product_skus(id);

ALTER TABLE "public"."product_skus"
  ADD CONSTRAINT "product_skus_product_model_id_fkey" FOREIGN KEY (product_model_id) REFERENCES public.product_models(id);

ALTER TABLE "public"."sap_bom_headers"
  ADD CONSTRAINT "sap_bom_headers_import_id_fkey" FOREIGN KEY (import_id) REFERENCES public.imports(id);

ALTER TABLE "public"."sap_bom_headers"
  ADD CONSTRAINT "sap_bom_headers_product_sku_id_fkey" FOREIGN KEY (product_sku_id) REFERENCES public.product_skus(id);

ALTER TABLE "public"."sap_bom_items"
  ADD CONSTRAINT "sap_bom_items_material_id_fkey" FOREIGN KEY (material_id) REFERENCES public.materials(id);

ALTER TABLE "public"."sap_bom_items"
  ADD CONSTRAINT "sap_bom_items_sap_bom_header_id_fkey" FOREIGN KEY (sap_bom_header_id) REFERENCES public.sap_bom_headers(id) ON DELETE CASCADE;

CREATE INDEX idx_eng_nodes_bom ON public.engineering_bom_nodes USING btree (engineering_bom_id);

CREATE INDEX idx_eng_nodes_parent ON public.engineering_bom_nodes USING btree (engineering_bom_id, parent_legacy_component_id);

CREATE INDEX idx_material_family ON public.materials USING btree (material_family_id);

CREATE INDEX idx_product_skus_legacy_colchon ON public.product_skus USING btree (legacy_colchon_id);

CREATE INDEX idx_product_skus_model ON public.product_skus USING btree (product_model_id);

CREATE INDEX idx_product_skus_sap ON public.product_skus USING btree (sap_material_code);

CREATE INDEX idx_sap_bom_parent ON public.sap_bom_headers USING btree (parent_material_code);

CREATE INDEX idx_sap_bom_sku ON public.sap_bom_headers USING btree (product_sku_id);

CREATE INDEX idx_sap_item_component ON public.sap_bom_items USING btree (component_code);

CREATE INDEX idx_sap_item_header ON public.sap_bom_items USING btree (sap_bom_header_id);

CREATE INDEX idx_sap_item_material ON public.sap_bom_items USING btree (material_id);

CREATE TRIGGER trg_engineering_nodes_updated_at
  BEFORE UPDATE ON public.engineering_bom_nodes
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_engineering_boms_updated_at
  BEFORE UPDATE ON public.engineering_boms
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_materials_updated_at
  BEFORE UPDATE ON public.materials
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_product_models_updated_at
  BEFORE UPDATE ON public.product_models
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE TRIGGER trg_product_skus_updated_at
  BEFORE UPDATE ON public.product_skus
  FOR EACH ROW
  EXECUTE FUNCTION public.set_updated_at();

CREATE EVENT TRIGGER "ensure_rls"
  ON ddl_command_end
  WHEN TAG IN ('CREATE TABLE', 'CREATE TABLE AS', 'SELECT INTO')
  EXECUTE FUNCTION "public"."rls_auto_enable"();

GRANT EXECUTE ON FUNCTION "public"."rls_auto_enable"() TO PUBLIC, "postgres";

GRANT EXECUTE ON FUNCTION "public"."set_updated_at"() TO PUBLIC, "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."engineering_bom_nodes" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."engineering_bom_nodes" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."engineering_bom_nodes" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."engineering_boms" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."engineering_boms" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."engineering_boms" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."imports" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."imports" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."imports" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."material_families" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."material_families" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."material_families" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."materials" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."materials" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."materials" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."product_models" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_models" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."product_models" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."product_skus" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."product_skus" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."product_skus" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."sap_bom_headers" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sap_bom_headers" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."sap_bom_headers" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."sap_bom_items" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."sap_bom_items" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."sap_bom_items" TO "service_role";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."validation_issues" TO "anon", "authenticated";

GRANT DELETE, INSERT, MAINTAIN, REFERENCES, SELECT, TRIGGER, TRUNCATE, UPDATE ON TABLE "public"."validation_issues" TO "postgres";

GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLE "public"."validation_issues" TO "service_role";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "anon";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "authenticated";

ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT MAINTAIN, REFERENCES, TRIGGER, TRUNCATE ON TABLES TO "service_role";

