-- ============================================================
-- LAMITEX · CONTROL DE COLCHONES CON ETIQUETAS QR
-- Empaque → Bodega → Producción (oficina)
--
-- Migración ADITIVA: solo crea tablas, funciones y políticas nuevas
-- con prefijo lmx_qr_. No modifica product_models, product_skus,
-- user_profiles ni ninguna otra tabla existente (solo las referencia).
-- ============================================================
BEGIN;

-- ------------------------------------------------------------
-- 1. ACCESO A LOS MÓDULOS QR
--    ADMIN     → los 4 módulos (los ADMIN del ERP también lo son)
--    PACKER    → solo Empaque
--    WAREHOUSE → solo Bodega
--    OFFICE    → solo Producción / reportes
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lmx_qr_user_access (
  user_id      uuid PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  module_role  text NOT NULL CHECK (module_role IN ('ADMIN','PACKER','WAREHOUSE','OFFICE')),
  display_name text,
  active       boolean NOT NULL DEFAULT true,
  created_at   timestamptz NOT NULL DEFAULT now(),
  updated_at   timestamptz NOT NULL DEFAULT now()
);
ALTER TABLE public.lmx_qr_user_access ENABLE ROW LEVEL SECURITY;

DROP TRIGGER IF EXISTS trg_lmx_qr_user_access_updated_at ON public.lmx_qr_user_access;
CREATE TRIGGER trg_lmx_qr_user_access_updated_at BEFORE UPDATE ON public.lmx_qr_user_access
FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- Rol efectivo del usuario actual en los módulos QR (NULL = sin acceso).
CREATE OR REPLACE FUNCTION public.lmx_qr_role()
RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT CASE
    WHEN public.has_any_role(ARRAY['ADMIN']) THEN 'ADMIN'
    ELSE (SELECT a.module_role FROM public.lmx_qr_user_access a WHERE a.user_id = auth.uid() AND a.active)
  END;
$$;

CREATE OR REPLACE FUNCTION public.lmx_qr_can(allowed text[])
RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = '' AS $$
  SELECT COALESCE(public.lmx_qr_role() = 'ADMIN' OR public.lmx_qr_role() = ANY (allowed), false);
$$;

REVOKE ALL ON FUNCTION public.lmx_qr_role() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.lmx_qr_can(text[]) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_role() TO authenticated;
GRANT EXECUTE ON FUNCTION public.lmx_qr_can(text[]) TO authenticated;

DROP POLICY IF EXISTS lmx_qr_access_select ON public.lmx_qr_user_access;
CREATE POLICY lmx_qr_access_select ON public.lmx_qr_user_access FOR SELECT TO authenticated
  USING (user_id = auth.uid() OR public.lmx_qr_can(ARRAY['ADMIN']));
DROP POLICY IF EXISTS lmx_qr_access_admin_write ON public.lmx_qr_user_access;
CREATE POLICY lmx_qr_access_admin_write ON public.lmx_qr_user_access FOR ALL TO authenticated
  USING (public.lmx_qr_can(ARRAY['ADMIN'])) WITH CHECK (public.lmx_qr_can(ARRAY['ADMIN']));

-- ------------------------------------------------------------
-- 2. LOTES DE IMPRESIÓN, LÍNEAS Y ETIQUETAS
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lmx_qr_batches (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  programmer        text NOT NULL CHECK (length(trim(programmer)) > 0),
  observation       text,
  sticker_width_mm  numeric(6,1) NOT NULL DEFAULT 100 CHECK (sticker_width_mm BETWEEN 20 AND 300),
  sticker_height_mm numeric(6,1) NOT NULL DEFAULT 50  CHECK (sticker_height_mm BETWEEN 15 AND 300),
  total_labels      integer NOT NULL DEFAULT 0,
  created_by        uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  created_at        timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS public.lmx_qr_batch_lines (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id       bigint NOT NULL REFERENCES public.lmx_qr_batches(id) ON DELETE CASCADE,
  product_sku_id bigint REFERENCES public.product_skus(id) ON DELETE SET NULL,
  sap_code       text NOT NULL,
  model_name     text NOT NULL,
  measure        text,
  quantity       integer NOT NULL CHECK (quantity BETWEEN 1 AND 2000),
  observation    text
);
CREATE INDEX IF NOT EXISTS lmx_qr_batch_lines_batch_idx ON public.lmx_qr_batch_lines(batch_id);

CREATE TABLE IF NOT EXISTS public.lmx_qr_labels (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code           text NOT NULL UNIQUE,
  batch_id       bigint NOT NULL REFERENCES public.lmx_qr_batches(id) ON DELETE RESTRICT,
  line_id        bigint NOT NULL REFERENCES public.lmx_qr_batch_lines(id) ON DELETE RESTRICT,
  seq            integer NOT NULL,
  product_sku_id bigint REFERENCES public.product_skus(id) ON DELETE SET NULL,
  sap_code       text NOT NULL,
  model_name     text NOT NULL,
  measure        text,
  created_at     timestamptz NOT NULL DEFAULT now(),
  -- Etapa 1: empaque (una sola vez)
  packed_at      timestamptz,
  packed_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  packed_manual  boolean,
  -- Etapa 2: bodega (una sola vez)
  received_at    timestamptz,
  received_by    uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  received_manual boolean,
  -- Anulación (etiqueta dañada / no usada)
  voided_at      timestamptz,
  voided_by      uuid REFERENCES auth.users(id) ON DELETE SET NULL,
  void_reason    text,
  CONSTRAINT lmx_qr_labels_stage_order CHECK (received_at IS NULL OR packed_at IS NOT NULL)
);
CREATE INDEX IF NOT EXISTS lmx_qr_labels_batch_idx    ON public.lmx_qr_labels(batch_id);
CREATE INDEX IF NOT EXISTS lmx_qr_labels_packed_idx   ON public.lmx_qr_labels(packed_at);
CREATE INDEX IF NOT EXISTS lmx_qr_labels_received_idx ON public.lmx_qr_labels(received_at);
CREATE INDEX IF NOT EXISTS lmx_qr_labels_sap_idx      ON public.lmx_qr_labels(sap_code);

-- Bloqueo definitivo: una vez registrada una etapa, ya no se puede cambiar ni borrar.
CREATE OR REPLACE FUNCTION public.lmx_qr_labels_lock()
RETURNS trigger LANGUAGE plpgsql SET search_path = '' AS $$
BEGIN
  IF TG_OP = 'DELETE' THEN
    RAISE EXCEPTION 'Las etiquetas QR no se pueden borrar; anúlalas.';
  END IF;
  IF OLD.packed_at IS NOT NULL AND NEW.packed_at IS DISTINCT FROM OLD.packed_at
     OR OLD.packed_by IS NOT NULL AND NEW.packed_by IS DISTINCT FROM OLD.packed_by THEN
    RAISE EXCEPTION 'La etiqueta % ya fue escaneada en empaque.', OLD.code;
  END IF;
  IF OLD.received_at IS NOT NULL AND NEW.received_at IS DISTINCT FROM OLD.received_at
     OR OLD.received_by IS NOT NULL AND NEW.received_by IS DISTINCT FROM OLD.received_by THEN
    RAISE EXCEPTION 'La etiqueta % ya fue escaneada en bodega.', OLD.code;
  END IF;
  IF NEW.code <> OLD.code OR NEW.sap_code <> OLD.sap_code OR NEW.batch_id <> OLD.batch_id THEN
    RAISE EXCEPTION 'Los datos de origen de la etiqueta no se pueden cambiar.';
  END IF;
  RETURN NEW;
END;
$$;
DROP TRIGGER IF EXISTS trg_lmx_qr_labels_lock ON public.lmx_qr_labels;
CREATE TRIGGER trg_lmx_qr_labels_lock BEFORE UPDATE OR DELETE ON public.lmx_qr_labels
FOR EACH ROW EXECUTE FUNCTION public.lmx_qr_labels_lock();

-- ------------------------------------------------------------
-- 3. BITÁCORA DE TODOS LOS INTENTOS DE ESCANEO (aceptados y rechazados)
-- ------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.lmx_qr_scans (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stage             text NOT NULL CHECK (stage IN ('PACK','WAREHOUSE')),
  scanned_code      text NOT NULL,
  label_id          bigint REFERENCES public.lmx_qr_labels(id) ON DELETE SET NULL,
  result            text NOT NULL CHECK (result IN ('OK','ALREADY_SCANNED','NOT_FOUND','MODEL_MISMATCH','NOT_PACKED','VOIDED')),
  expected_sap_code text,
  label_sap_code    text,
  manual            boolean NOT NULL DEFAULT false,
  scanned_by        uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  scanned_by_name   text,
  scanned_at        timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS lmx_qr_scans_at_idx ON public.lmx_qr_scans(scanned_at);
CREATE INDEX IF NOT EXISTS lmx_qr_scans_label_idx ON public.lmx_qr_scans(label_id);

ALTER TABLE public.lmx_qr_batches     ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lmx_qr_batch_lines ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lmx_qr_labels      ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lmx_qr_scans       ENABLE ROW LEVEL SECURITY;

-- Lectura: cualquiera con acceso a algún módulo QR. Escritura directa: nadie;
-- todo pasa por las funciones de abajo, que validan rol y reglas.
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['lmx_qr_batches','lmx_qr_batch_lines','lmx_qr_labels','lmx_qr_scans'] LOOP
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON public.%I FROM authenticated', t);
    EXECUTE format('GRANT SELECT ON public.%I TO authenticated', t);
    EXECUTE format('DROP POLICY IF EXISTS lmx_qr_read ON public.%I', t);
    EXECUTE format('CREATE POLICY lmx_qr_read ON public.%I FOR SELECT TO authenticated USING (public.lmx_qr_role() IS NOT NULL)', t);
  END LOOP;
END
$$;
REVOKE ALL ON public.lmx_qr_user_access FROM anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.lmx_qr_user_access TO authenticated;

-- Catálogo de colchones para los módulos QR (sin dar acceso de lectura al resto del ERP).
CREATE OR REPLACE FUNCTION public.lmx_qr_catalog()
RETURNS TABLE (sku_id bigint, sap_code text, model_name text, measure text, sap_name text)
LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF public.lmx_qr_role() IS NULL THEN RAISE EXCEPTION 'Sin acceso a los módulos QR.'; END IF;
  RETURN QUERY
    SELECT s.id, trim(s.sap_material_code), COALESCE(m.canonical_name, m.catalog_name_original), s.commercial_measure, s.sap_name_original
    FROM public.product_skus s JOIN public.product_models m ON m.id = s.product_model_id
    WHERE s.active AND m.active AND COALESCE(trim(s.sap_material_code), '') <> ''
    ORDER BY 3, 4, 2;
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_catalog() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_catalog() TO authenticated;

-- ------------------------------------------------------------
-- 4. GENERAR UN LOTE DE ETIQUETAS (ADMIN)
--    p_lines: [{"sku_id":1,"quantity":20,"observation":"..."}]
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lmx_qr_create_batch(
  p_programmer text, p_observation text, p_width_mm numeric, p_height_mm numeric, p_lines jsonb)
RETURNS bigint LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_batch bigint; v_line bigint; v_total integer := 0; l jsonb; s record; q integer; i integer; v_code text;
BEGIN
  IF NOT public.lmx_qr_can(ARRAY['ADMIN']) THEN RAISE EXCEPTION 'Solo el administrador puede generar etiquetas.'; END IF;
  IF jsonb_typeof(p_lines) <> 'array' OR jsonb_array_length(p_lines) = 0 THEN RAISE EXCEPTION 'Agrega al menos un colchón.'; END IF;

  INSERT INTO public.lmx_qr_batches (programmer, observation, sticker_width_mm, sticker_height_mm)
  VALUES (trim(p_programmer), NULLIF(trim(p_observation), ''), p_width_mm, p_height_mm) RETURNING id INTO v_batch;

  FOR l IN SELECT * FROM jsonb_array_elements(p_lines) LOOP
    q := (l->>'quantity')::integer;
    SELECT sk.id, trim(sk.sap_material_code) AS sap, COALESCE(m.canonical_name, m.catalog_name_original) AS model, sk.commercial_measure AS measure
      INTO s FROM public.product_skus sk JOIN public.product_models m ON m.id = sk.product_model_id
      WHERE sk.id = (l->>'sku_id')::bigint;
    IF s.id IS NULL OR COALESCE(s.sap, '') = '' THEN RAISE EXCEPTION 'Colchón % no encontrado o sin código SAP.', l->>'sku_id'; END IF;

    INSERT INTO public.lmx_qr_batch_lines (batch_id, product_sku_id, sap_code, model_name, measure, quantity, observation)
    VALUES (v_batch, s.id, s.sap, s.model, s.measure, q, NULLIF(trim(l->>'observation'), '')) RETURNING id INTO v_line;

    FOR i IN 1..q LOOP
      LOOP
        v_code := 'LMX-' || upper(substr(replace(gen_random_uuid()::text, '-', ''), 1, 12));
        EXIT WHEN NOT EXISTS (SELECT 1 FROM public.lmx_qr_labels WHERE code = v_code);
      END LOOP;
      INSERT INTO public.lmx_qr_labels (code, batch_id, line_id, seq, product_sku_id, sap_code, model_name, measure)
      VALUES (v_code, v_batch, v_line, i, s.id, s.sap, s.model, s.measure);
    END LOOP;
    v_total := v_total + q;
  END LOOP;

  IF v_total > 5000 THEN RAISE EXCEPTION 'Máximo 5000 etiquetas por lote.'; END IF;
  UPDATE public.lmx_qr_batches SET total_labels = v_total WHERE id = v_batch;
  RETURN v_batch;
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_create_batch(text, text, numeric, numeric, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_create_batch(text, text, numeric, numeric, jsonb) TO authenticated;

-- ------------------------------------------------------------
-- 5. REGISTRAR UN ESCANEO (empaque o bodega) — una sola vez por etapa
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lmx_qr_register_scan(
  p_stage text, p_code text, p_expected_sap text, p_manual boolean)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE
  v_code text := upper(trim(COALESCE(p_code, '')));
  v_expected text := NULLIF(trim(COALESCE(p_expected_sap, '')), '');
  v_name text; lb public.lmx_qr_labels; v_result text; v_msg text;
BEGIN
  IF p_stage = 'PACK' AND NOT public.lmx_qr_can(ARRAY['PACKER']) THEN RAISE EXCEPTION 'Sin acceso al módulo de empaque.'; END IF;
  IF p_stage = 'WAREHOUSE' AND NOT public.lmx_qr_can(ARRAY['WAREHOUSE']) THEN RAISE EXCEPTION 'Sin acceso al módulo de bodega.'; END IF;
  IF p_stage NOT IN ('PACK','WAREHOUSE') THEN RAISE EXCEPTION 'Etapa no válida.'; END IF;
  IF p_stage = 'PACK' AND v_expected IS NULL THEN RAISE EXCEPTION 'Selecciona el colchón que estás empacando.'; END IF;
  IF v_code = '' THEN RAISE EXCEPTION 'Código vacío.'; END IF;

  SELECT COALESCE(a.display_name, p.display_name, u.email) INTO v_name
    FROM auth.users u
    LEFT JOIN public.lmx_qr_user_access a ON a.user_id = u.id
    LEFT JOIN public.user_profiles p ON p.user_id = u.id
    WHERE u.id = auth.uid();

  -- FOR UPDATE: dos celulares escaneando la misma etiqueta a la vez → solo uno gana.
  SELECT * INTO lb FROM public.lmx_qr_labels WHERE code = v_code FOR UPDATE;

  IF lb.id IS NULL THEN
    v_result := 'NOT_FOUND'; v_msg := 'Esta etiqueta no existe en el sistema.';
  ELSIF lb.voided_at IS NOT NULL THEN
    v_result := 'VOIDED'; v_msg := 'Esta etiqueta fue anulada.';
  ELSIF p_stage = 'PACK' AND lb.packed_at IS NOT NULL THEN
    v_result := 'ALREADY_SCANNED'; v_msg := 'Esta etiqueta ya fue escaneada en empaque y está bloqueada.';
  ELSIF p_stage = 'WAREHOUSE' AND lb.received_at IS NOT NULL THEN
    v_result := 'ALREADY_SCANNED'; v_msg := 'Esta etiqueta ya fue recibida en bodega y está bloqueada.';
  ELSIF v_expected IS NOT NULL AND v_expected <> lb.sap_code THEN
    v_result := 'MODEL_MISMATCH'; v_msg := 'La etiqueta es de otro colchón: ' || lb.model_name || COALESCE(' ' || lb.measure, '') || ' (' || lb.sap_code || ').';
  ELSIF p_stage = 'WAREHOUSE' AND lb.packed_at IS NULL THEN
    v_result := 'NOT_PACKED'; v_msg := 'Esta etiqueta no fue escaneada en empaque. Devuélvela a empaque.';
  ELSE
    v_result := 'OK';
    IF p_stage = 'PACK' THEN
      UPDATE public.lmx_qr_labels SET packed_at = now(), packed_by = auth.uid(), packed_manual = COALESCE(p_manual, false) WHERE id = lb.id RETURNING * INTO lb;
      v_msg := 'Empaque registrado.';
    ELSE
      UPDATE public.lmx_qr_labels SET received_at = now(), received_by = auth.uid(), received_manual = COALESCE(p_manual, false) WHERE id = lb.id RETURNING * INTO lb;
      v_msg := 'Ingreso a bodega registrado.';
    END IF;
  END IF;

  INSERT INTO public.lmx_qr_scans (stage, scanned_code, label_id, result, expected_sap_code, label_sap_code, manual, scanned_by, scanned_by_name)
  VALUES (p_stage, left(v_code, 120), lb.id, v_result, v_expected, lb.sap_code, COALESCE(p_manual, false), auth.uid(), v_name);

  RETURN jsonb_build_object(
    'ok', v_result = 'OK', 'result', v_result, 'message', v_msg, 'code', v_code,
    'sap_code', lb.sap_code, 'model_name', lb.model_name, 'measure', lb.measure,
    'packed_at', lb.packed_at, 'received_at', lb.received_at, 'at', now());
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_register_scan(text, text, text, boolean) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_register_scan(text, text, text, boolean) TO authenticated;

-- ------------------------------------------------------------
-- 6. ANULAR UNA ETIQUETA NO USADA (ADMIN)
-- ------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.lmx_qr_void_label(p_code text, p_reason text)
RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
BEGIN
  IF NOT public.lmx_qr_can(ARRAY['ADMIN']) THEN RAISE EXCEPTION 'Solo el administrador puede anular etiquetas.'; END IF;
  IF COALESCE(trim(p_reason), '') = '' THEN RAISE EXCEPTION 'Indica el motivo de la anulación.'; END IF;
  UPDATE public.lmx_qr_labels SET voided_at = now(), voided_by = auth.uid(), void_reason = trim(p_reason)
   WHERE code = upper(trim(p_code)) AND voided_at IS NULL AND received_at IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'La etiqueta no existe, ya está anulada o ya ingresó a bodega.'; END IF;
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_void_label(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_void_label(text, text) TO authenticated;

COMMIT;
