-- ============================================================
-- LAMITEX · CONTROL QR: PROGRAMA DIARIO Y CIERRE DEL DÍA
-- Aditivo: solo tablas y funciones nuevas lmx_qr_.
-- ============================================================
BEGIN;

-- Programa de producción del día (lo que el planificador manda a la planta), por código SAP.
CREATE TABLE IF NOT EXISTS public.lmx_qr_daily_plans (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_date   date NOT NULL,
  sap_code    text NOT NULL,
  model_name  text NOT NULL,
  quantity    integer NOT NULL CHECK (quantity BETWEEN 0 AND 100000),
  source      text NOT NULL DEFAULT 'MANUAL' CHECK (source IN ('MANUAL','PLAN_MAESTRO','EXCEL')),
  mps_run_id  uuid,
  notes       text,
  created_by  uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  updated_at  timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lmx_qr_daily_plans_day_sap UNIQUE (plan_date, sap_code)
);

-- Cierre del día por etapa: empaque y bodega avisan a producción que terminaron.
CREATE TABLE IF NOT EXISTS public.lmx_qr_day_closures (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  close_date     date NOT NULL,
  stage          text NOT NULL CHECK (stage IN ('PACK','WAREHOUSE')),
  total_ok       integer NOT NULL DEFAULT 0,
  notes          text,
  closed_by      uuid DEFAULT auth.uid() REFERENCES auth.users(id) ON DELETE SET NULL,
  closed_by_name text,
  closed_at      timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT lmx_qr_day_closures_day_stage UNIQUE (close_date, stage)
);

ALTER TABLE public.lmx_qr_daily_plans  ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lmx_qr_day_closures ENABLE ROW LEVEL SECURITY;

DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['lmx_qr_daily_plans','lmx_qr_day_closures'] LOOP
    EXECUTE format('REVOKE ALL ON public.%I FROM anon', t);
    EXECUTE format('REVOKE INSERT, UPDATE, DELETE ON public.%I FROM authenticated', t);
    EXECUTE format('GRANT SELECT ON public.%I TO authenticated', t);
    EXECUTE format('GRANT SELECT, INSERT, UPDATE, DELETE ON public.%I TO service_role', t);
    EXECUTE format('DROP POLICY IF EXISTS lmx_qr_read ON public.%I', t);
    EXECUTE format('CREATE POLICY lmx_qr_read ON public.%I FOR SELECT TO authenticated USING (public.lmx_qr_role() IS NOT NULL)', t);
  END LOOP;
END
$$;

-- Guarda (reemplaza) el programa de un día. p_lines: [{"sap_code":"3C45327","model_name":"...","quantity":20}]
CREATE OR REPLACE FUNCTION public.lmx_qr_save_plan(p_date date, p_lines jsonb, p_source text, p_mps_run uuid, p_notes text)
RETURNS integer LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE l jsonb; n integer := 0;
BEGIN
  IF NOT public.lmx_qr_can(ARRAY['ADMIN']) THEN RAISE EXCEPTION 'Solo el administrador puede cargar el programa.'; END IF;
  IF p_date IS NULL THEN RAISE EXCEPTION 'Elige la fecha del programa.'; END IF;
  IF jsonb_typeof(p_lines) <> 'array' THEN RAISE EXCEPTION 'Programa no válido.'; END IF;
  DELETE FROM public.lmx_qr_daily_plans WHERE plan_date = p_date;
  FOR l IN SELECT * FROM jsonb_array_elements(p_lines) LOOP
    IF COALESCE(trim(l->>'sap_code'), '') = '' OR COALESCE((l->>'quantity')::integer, 0) <= 0 THEN CONTINUE; END IF;
    INSERT INTO public.lmx_qr_daily_plans (plan_date, sap_code, model_name, quantity, source, mps_run_id, notes)
    VALUES (p_date, upper(trim(l->>'sap_code')), COALESCE(NULLIF(trim(l->>'model_name'), ''), upper(trim(l->>'sap_code'))), (l->>'quantity')::integer,
            COALESCE(p_source, 'MANUAL'), p_mps_run, NULLIF(trim(p_notes), ''))
    ON CONFLICT (plan_date, sap_code) DO UPDATE SET quantity = public.lmx_qr_daily_plans.quantity + EXCLUDED.quantity, updated_at = now();
    n := n + 1;
  END LOOP;
  RETURN n;
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_save_plan(date, jsonb, text, uuid, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_save_plan(date, jsonb, text, uuid, text) TO authenticated;

-- "Terminar el día": registra el cierre de la etapa con el total aceptado de hoy (hora de Ecuador).
-- Se puede volver a cerrar si se escanearon más colchones después; se actualiza la hora y el total.
CREATE OR REPLACE FUNCTION public.lmx_qr_close_day(p_stage text, p_notes text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path = '' AS $$
DECLARE v_day date := (now() AT TIME ZONE 'America/Guayaquil')::date; v_total integer; v_name text; r public.lmx_qr_day_closures;
BEGIN
  IF p_stage = 'PACK' AND NOT public.lmx_qr_can(ARRAY['PACKER']) THEN RAISE EXCEPTION 'Sin acceso al módulo de empaque.'; END IF;
  IF p_stage = 'WAREHOUSE' AND NOT public.lmx_qr_can(ARRAY['WAREHOUSE']) THEN RAISE EXCEPTION 'Sin acceso al módulo de bodega.'; END IF;
  IF p_stage NOT IN ('PACK','WAREHOUSE') THEN RAISE EXCEPTION 'Etapa no válida.'; END IF;
  SELECT count(*) INTO v_total FROM public.lmx_qr_labels
   WHERE CASE WHEN p_stage = 'PACK' THEN (packed_at AT TIME ZONE 'America/Guayaquil')::date ELSE (received_at AT TIME ZONE 'America/Guayaquil')::date END = v_day;
  SELECT COALESCE(a.display_name, p.display_name, u.email) INTO v_name
    FROM auth.users u LEFT JOIN public.lmx_qr_user_access a ON a.user_id = u.id LEFT JOIN public.user_profiles p ON p.user_id = u.id WHERE u.id = auth.uid();
  INSERT INTO public.lmx_qr_day_closures (close_date, stage, total_ok, notes, closed_by, closed_by_name)
  VALUES (v_day, p_stage, v_total, NULLIF(trim(p_notes), ''), auth.uid(), v_name)
  ON CONFLICT (close_date, stage) DO UPDATE SET total_ok = EXCLUDED.total_ok, notes = EXCLUDED.notes, closed_by = EXCLUDED.closed_by, closed_by_name = EXCLUDED.closed_by_name, closed_at = now()
  RETURNING * INTO r;
  RETURN to_jsonb(r);
END;
$$;
REVOKE ALL ON FUNCTION public.lmx_qr_close_day(text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.lmx_qr_close_day(text, text) TO authenticated;

COMMIT;
